name = "compfiles"
defaultTargets = ["ProblemExtraction", "Compfiles", "buildWebpage", "extractProblems", "checkSolution"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.multiGoal = true
weak.linter.style.cdot = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.24.0"

[[require]]
name = "tryAtEachStep"
git = "https://github.com/dwrensha/tryAtEachStep"
rev = "lean-v4.24.0"

[[lean_lib]]
name = "ProblemExtraction"

[[lean_lib]]
name = "Compfiles"

[[lean_exe]]
name = "buildWebpage"
root = "scripts.buildWebpage"
supportInterpreter = true

[[lean_exe]]
name = "extractProblems"
root = "scripts.extractProblems"
supportInterpreter = true

[[lean_exe]]
name = "checkSolution"
root = "scripts.checkSolution"
supportInterpreter = true
